using System;
using System.Collections.Generic;
using System.Text;

namespace MyCloudProject.Common
{
    /// <summary>
    /// Defines the contract for the result of an experiment.
    /// </summary>
    public interface IExperimentResult
    {
        /// <summary>
        /// Gets or sets the unique identifier for the experiment result.
        /// This ID corresponds to the experiment that produced this result.
        /// </summary>
        string ExperimentId { get; set; }

        /// <summary>
        /// Gets or sets the URL of the file that contains the input data used in the experiment.
        /// This URL points to the location where the input file is stored.
        /// </summary>
        public string InputFileUrl { get; set; }

        /// <summary>
        /// Gets or sets the UTC date and time when the experiment started.
        /// This property helps track when the experiment began.
        /// </summary>
        DateTime? StartTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the UTC date and time when the experiment ended.
        /// This property helps track when the experiment completed.
        /// </summary>
        DateTime? EndTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the duration of the experiment.
        /// This represents the total time taken for the experiment to complete, calculated as the difference between start and end times.
        /// </summary>
        public TimeSpan Duration { get; set; }

        /// <summary>
        /// Gets or sets the file paths or URLs of the output files generated by the experiment.
        /// This property contains the results produced by the experiment, usually in the form of files or URLs.
        /// </summary>
        public string OutputFiles { get; set; }
    }
}