using Azure;
using Azure.Data.Tables;
using MyCloudProject.Common;
using System;
using System.Collections.Generic;
using System.Text;

namespace MyExperiment
{
    /// <summary>
    /// Represents the result of an experiment, including metadata and results.
    /// This class is designed to work with Azure Table Storage and implements
    /// the ITableEntity and IExperimentResult interfaces.
    /// </summary>
    public class ExperimentResult : ITableEntity, IExperimentResult
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExperimentResult"/> class.
        /// </summary>
        /// <param name="partitionKey">The partition key for the Azure Table Storage entity.</param>
        /// <param name="rowKey">The row key for the Azure Table Storage entity.</param>
        public ExperimentResult(string partitionKey, string rowKey)
        {
            this.PartitionKey = partitionKey;
            this.RowKey = rowKey;
        }

        /// <summary>
        /// Gets or sets the partition key for the Azure Table Storage entity.
        /// </summary>
        public string PartitionKey { get; set; }

        /// <summary>
        /// Gets or sets the row key for the Azure Table Storage entity.
        /// </summary>
        public string RowKey { get; set; }

        /// <summary>
        /// Gets or sets the timestamp for when the entity was last modified.
        /// </summary>
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the ETag for the entity, used for concurrency control.
        /// </summary>
        public ETag ETag { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the experiment.
        /// </summary>
        public string ExperimentId { get; set; }

        /// <summary>
        /// Gets or sets the name of the experiment.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a description of the experiment.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the start time of the experiment in UTC.
        /// </summary>
        public DateTime? StartTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the end time of the experiment in UTC.
        /// </summary>
        public DateTime? EndTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the duration of the experiment in seconds.
        /// </summary>
        public long DurationSec { get; set; }

        /// <summary>
        /// Gets or sets the URL of the input file used for the experiment.
        /// </summary>
        public string InputFileUrl { get; set; }

        /// <summary>
        /// Gets or sets a comma-separated list of output file URLs generated by the experiment.
        /// </summary>
        public string OutputFiles { get; set; }

        // Additional properties related to experiment results.

        /// <summary>
        /// Gets or sets the accuracy of the experiment results.
        /// </summary>
        public float Accuracy { get; set; }

        /// <summary>
        /// Gets or sets the duration of the experiment as a TimeSpan.
        /// </summary>
        public TimeSpan Duration { get; set; }

        /// <summary>
        /// Gets or sets the pop receipt used to confirm that the result has been processed.
        /// </summary>
        public string PopReceipt { get; set; }

        /// <summary>
        /// Gets or sets the test case identifier associated with the experiment.
        /// </summary>
        public string testcase { get; set; }

        /// <summary>
        /// Gets or sets any comments or additional notes related to the experiment.
        /// </summary>
        public string Comments { get; set; }
    }
}
